### ISSUE TITLE
Simulate compute asset containers

### ISSUE THREAD

**Issue by LourensVeen** [SecConNet/mahiru#5]
Computing is currently done inside the JobRun class. Instead, we should have some classes representing assets. These classes would model container images, and they would replace the current any-object data assets in the AssetStore. JobRun would then obtain them from the relevant store, and run them with the input assets, probably by calling a run() method and passing a dictionary of input assets.

Class hierarchy: Asset{} < ComputeAsset{run(inputs: Dict)} so that we can later add a DataAsset class for those.

**Comment by svenvanderburg** [comment]
@LourensVeen do you agree that this issue is fixed by https://github.com/SecConNet/proof_of_concept/pull/11? So then we can close this issue?

**Comment by LourensVeen** [comment]
Hmm, well just going by what's written I still miss the "JobRun would then obtain them from the relevant store" part. That could also be split off into a separate PBI/Issue though.

**Comment by LourensVeen** [comment]
Moved that to #13, closing this. Thanks for implementing this!

**Comment by svenvanderburg** [comment]
Bueno!
